### PR TITLE
Replace hard coded path

### LINKED ISSUE #12: Error:D:\workspace\leying\src\main\AndroidManifest.xml (系统找不到指定的路径。)
Don't support sourceSets,main config.

### PR DESCRIPTION
**Pull request by xfumihiro**
Fixes #12 and #16

### CODE REVIEW

**Comment by wogenhaosini** [comment]
I'm still kind of thing happens
Error:D:\workspace\leying\src\main\AndroidManifest.xml (系统找不到指定的路径。)  #12

**Comment by xfumihiro** [comment]
@wogenhaosini are you using the latest 0.1.3-SNAPSHOT?

**Comment by wogenhaosini** [comment]
no，I do not know 0.1.3-SNAPSHOT.

**Comment by Young55555** [comment]
EDINOROD

**Pull request merged**
